#!/bin/bash

# =============================================================================
# Performance Regression Checker Script
# =============================================================================
#
# Checks for performance regressions by comparing current metrics to baseline.
# Uses JSON metric files generated by XCTest performance tests.
#
# Usage: ./Scripts/check-performance-regression.sh [baseline_file] [current_file]
#
# Requirements:
#   - jq (install with: brew install jq)
#   - bc (install with: brew install bc)
#
# =============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
BASELINE_FILE="${1:-$PROJECT_DIR/Tests/Performance/baseline-metrics.json}"
CURRENT_FILE="${2:-$PROJECT_DIR/Tests/Performance/current-metrics.json}"
OUTPUT_DIR="$PROJECT_DIR/Tests/Performance"
THRESHOLD=0.10  # 10% regression threshold

echo "======================================"
echo "Performance Regression Checker"
echo "======================================"
echo "Baseline: $BASELINE_FILE"
echo "Current:  $CURRENT_FILE"
echo "Threshold: ${THRESHOLD}%"
echo ""

# Check if jq is installed
if ! command -v jq &> /dev/null; then
    echo "❌ Error: jq not found"
    echo ""
    echo "Install with: brew install jq"
    echo ""
    exit 1
fi

# Check if bc is installed
if ! command -v bc &> /dev/null; then
    echo "❌ Error: bc not found"
    echo ""
    echo "Install with: brew install bc"
    echo ""
    exit 1
fi

# Check if baseline exists
if [ ! -f "$BASELINE_FILE" ]; then
    echo "⚠️  Warning: Baseline metrics not found at $BASELINE_FILE"
    echo ""
    echo "Creating baseline from current metrics..."
    mkdir -p "$(dirname "$BASELINE_FILE")"
    cp "$CURRENT_FILE" "$BASELINE_FILE"
    echo "✅ Baseline created from current metrics"
    echo ""
    exit 0
fi

# Check if current exists
if [ ! -f "$CURRENT_FILE" ]; then
    echo "❌ Error: Current metrics not found at $CURRENT_FILE"
    echo ""
    echo "Run performance tests first to generate current metrics"
    echo ""
    exit 1
fi

echo "Analyzing performance metrics..."
echo ""

# Counters
total_metrics=0
regressions=0
improvements=0
stable=0

# Temporary file for processing
temp_file=$(mktemp)

# Merge baseline and current metrics
jq -s '
  .[0] as $baseline |
  .[1] as $current |
  ($baseline | to_entries) |
  map({
    name: .key,
    baseline: $baseline[.key],
    current: ($current[.key] // 0)
  })
' "$BASELINE_FILE" "$CURRENT_FILE" > "$temp_file"

# Process each metric
while IFS= read -r metric; do
  name=$(echo "$metric" | jq -r '.name')
  baseline=$(echo "$metric" | jq -r '.baseline')
  current=$(echo "$metric" | jq -r '.current')

  # Skip if baseline is 0
  if [ "$baseline" == "0" ] || [ "$baseline" == "null" ]; then
    echo "⏭️  SKIP: $name (no baseline)"
    continue
  fi

  # Skip if current is 0 or null
  if [ "$current" == "0" ] || [ "$current" == "null" ]; then
    echo "⚠️  WARNING: $name (no current value)"
    continue
  fi

  total_metrics=$((total_metrics + 1))

  # Calculate percentage change
  change=$(echo "scale=4; ($current - $baseline) / $baseline * 100" | bc)
  abs_change=${change#-}  # Absolute value

  # Format change for display
  change_formatted=$(printf "%.2f" "$change")

  # Check if regression exceeds threshold
  is_regression=$(echo "$abs_change > $THRESHOLD * 100" | bc -l)

  if [ "$is_regression" == "1" ]; then
    echo "⚠️  REGRESSION: $name"
    echo "     Baseline: ${baseline}s"
    echo "     Current:  ${current}s"
    echo "     Change:   +${change_formatted}%"

    regressions=$((regressions + 1))
  elif [ "$change" == "0" ]; then
    echo "✅ OK: $name (no change)"
    stable=$((stable + 1))
  else
    # Check if improvement (negative change beyond threshold)
    is_improvement=$(echo "$change < -$THRESHOLD * 100" | bc -l)

    if [ "$is_improvement" == "1" ]; then
      echo "🚀 IMPROVEMENT: $name"
      echo "     Baseline: ${baseline}s"
      echo "     Current:  ${current}s"
      echo "     Change:   ${change_formatted}%"

      improvements=$((improvements + 1))
    else
      echo "✅ OK: $name (${change_formatted}%)"
      stable=$((stable + 1))
    fi
  fi

  echo ""
done < <(jq -c '.[]' "$temp_file")

# Clean up temp file
rm -f "$temp_file"

echo "======================================"
echo "Performance Regression Results"
echo "======================================"
echo "Total metrics analyzed: $total_metrics"
echo "Regressions:             $regressions"
echo "Improvements:             $improvements"
echo "Stable:                   $stable"
echo ""

# Exit with appropriate code
if [ $regressions -gt 0 ]; then
  echo "❌ Performance regressions detected!"
  echo ""
  echo "Please review the failing metrics above."
  echo "If the regressions are acceptable, update the baseline:"
  echo "  cp '$CURRENT_FILE' '$BASELINE_FILE'"
  echo ""
  exit 1
else
  echo "✅ No performance regressions detected"
  echo ""
  exit 0
fi
